services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - aerospike_db
      - aerospike_cache
      - clickhouse
    environment:
      AEROSPIKE_DB_HOST: aerospike_db
      AEROSPIKE_DB_PORT: 3000
      AEROSPIKE_CACHE_HOST: aerospike_cache
      AEROSPIKE_CACHE_PORT: 3000
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: "username"
      CLICKHOUSE_PASSWORD: "password"
      CLICKHOUSE_DB: "database"
    networks:
      - app-network

  aerospike_db:
    image: aerospike/aerospike-server:latest
    ports:
      - "3000"
      - "3001" # Fabric port
      - "3002" # Mesh port
      - "3003" # Info port
    volumes:
      - aerospike_db_data:/opt/aerospike/data
    environment:
      NAMESPACE: db
    networks:
      - app-network

  aerospike_cache:
    image: aerospike/aerospike-server:latest
    ports:
      - "3000"
      - "3001"
      - "3002"
      - "3003"
    volumes:
      - aerospike_cache_data:/opt/aerospike/data
    environment:
      NAMESPACE: cache
    networks:
      - app-network

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123"
      - "9000"
    environment:
      CLICKHOUSE_USER: "username"
      CLICKHOUSE_PASSWORD: "password"
      CLICKHOUSE_DB: "database"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  aerospike_db_data:
  aerospike_cache_data:
  clickhouse_data:


